/// Application-wide constants for timeouts, limits, intervals and security
/// thresholds. All durations are expressed as [Duration] objects; monetary and
/// quantity limits are plain [double] / [int] values so they can be used in
/// validators without conversion.
///
/// Requirements: 13.1, 13.5
class AppConstants {
  AppConstants._(); // prevent instantiation

  // ── Network timeouts ──────────────────────────────────────────────────────

  /// Maximum time to wait for a TCP connection to be established.
  static const Duration networkConnectionTimeout = Duration(seconds: 30);

  /// Maximum time to wait for the server to send the first response byte.
  static const Duration networkReceiveTimeout = Duration(seconds: 30);

  /// Maximum time to wait while sending a request body to the server.
  static const Duration networkSendTimeout = Duration(seconds: 30);

  /// Timeout used when downloading / syncing the product catalog on startup
  /// (Requirement 11.2, 11.5).
  static const Duration catalogSyncTimeout = Duration(seconds: 30);

  /// Timeout in milliseconds for catalog sync (for Dio options)
  static const int catalogSyncTimeoutMs = 30000;

  // ── Sync intervals ────────────────────────────────────────────────────────

  /// Target interval between background sync cycles (Requirement 10.3).
  static const Duration syncInterval = Duration(minutes: 5);

  /// Maximum allowed drift from the target sync interval before it is logged
  /// and the next cycle is adjusted (Requirement 10.4).
  static const Duration syncDriftTolerance = Duration(seconds: 30);

  /// Maximum number of transactions included in a single sync batch
  /// (Requirement 10.3).
  static const int syncBatchSize = 100;

  // ── Authentication ────────────────────────────────────────────────────────

  /// Number of consecutive failed sign-in attempts before the button is
  /// locked (Requirement 1.3, 1.5).
  static const int authMaxFailedAttempts = 3;

  /// Duration for which the sign-in button is disabled after reaching
  /// [authMaxFailedAttempts] (Requirement 1.5).
  static const Duration authLockoutDuration = Duration(seconds: 30);

  /// Maximum time the app may remain in the background before the session is
  /// invalidated and the user must re-authenticate (Requirement 1.6, 1.7).
  static const Duration backgroundSessionTimeout = Duration(hours: 12);

  // ── Anti-fraud cancellation window ────────────────────────────────────────

  /// A sale can only be cancelled within this window after it was recorded
  /// (Requirement 6.1, 6.5).
  static const Duration cancellationWindow = Duration(minutes: 5);

  // ── Monetary limits ───────────────────────────────────────────────────────

  /// Maximum value accepted as Fondo_de_Cambio (opening balance) and as the
  /// counted-cash amount during Corte (Requirement 3.6, 9.2).
  static const double fondoDeCambioMax = 999999.99;

  /// Minimum valid value for Fondo_de_Cambio; zero is explicitly allowed
  /// (Requirement 3.7).
  static const double fondoDeCambioMin = 0.00;

  /// Maximum amount allowed for a single expense entry (Requirement 7.3).
  static const double expenseAmountMax = 999999.99;

  /// Minimum valid expense amount — must be strictly positive (Requirement 7.3).
  static const double expenseAmountMin = 0.01;

  // ── Product / quantity limits ─────────────────────────────────────────────

  /// Maximum quantity allowed for a single product line in a sale
  /// (Requirement 5.4, 5.8).
  static const int productQuantityMax = 999999999;

  /// Minimum valid product quantity — must be at least 1 (Requirement 5.8).
  static const int productQuantityMin = 1;

  // ── Text length limits ────────────────────────────────────────────────────

  /// Maximum character length for an expense description (Requirement 7.5).
  static const int expenseDescriptionMaxLength = 100;

  /// Maximum character length for a business name (Requirement 12.6).
  static const int businessNameMaxLength = 60;

  // ── QR code ───────────────────────────────────────────────────────────────

  /// Validity period for a QR code generated by the Patron to link a Cajero
  /// (Requirement 2.4).
  static const Duration qrCodeValidity = Duration(hours: 24);

  /// Maximum number of consecutive failed QR scan attempts before the scanner
  /// is locked (Requirement 2.5).
  static const int qrMaxFailedAttempts = 3;
}
